name: main
description: A new Flutter project.
publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Git-based modules
  module_a:
    git:
      url: https://github.com/art-dev3/module-a.git

  module_b:
    git:
      url: https://github.com/art-dev3/module-b.git

  # iOS style icons
  cupertino_icons: ^1.0.8
  dynamic_widget: ^6.0.0
  http: ^0.13.6
  stac: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  

  # To add assets to your application, uncomment and use like below:
  assets:
    - assets/test.json
  #   - images/
  #   - assets/icons/

  # To add custom fonts to your application:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
