// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChRAdVR-2sf6VIN97vexHdi05NEDvWbAA',
    appId: '1:137565283895:web:493d847a0200e735a3c1b2',
    messagingSenderId: '137565283895',
    projectId: 'asianlink-b0111',
    authDomain: 'asianlink-b0111.firebaseapp.com',
    storageBucket: 'asianlink-b0111.firebasestorage.app',
    measurementId: 'G-PCB8QZTD28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcaKmCAOEpFU7AhhDA2H3G_wgpI8occEs',
    appId: '1:137565283895:android:b7efa31097c21c5ca3c1b2',
    messagingSenderId: '137565283895',
    projectId: 'asianlink-b0111',
    storageBucket: 'asianlink-b0111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj_fgb4t1E9Wwixb3Je3pGD8qWJWWn_OY',
    appId: '1:137565283895:ios:801f3f6690d9afdda3c1b2',
    messagingSenderId: '137565283895',
    projectId: 'asianlink-b0111',
    storageBucket: 'asianlink-b0111.firebasestorage.app',
    iosBundleId: 'com.example.asianlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj_fgb4t1E9Wwixb3Je3pGD8qWJWWn_OY',
    appId: '1:137565283895:ios:801f3f6690d9afdda3c1b2',
    messagingSenderId: '137565283895',
    projectId: 'asianlink-b0111',
    storageBucket: 'asianlink-b0111.firebasestorage.app',
    iosBundleId: 'com.example.asianlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChRAdVR-2sf6VIN97vexHdi05NEDvWbAA',
    appId: '1:137565283895:web:4c6df608173ec6a9a3c1b2',
    messagingSenderId: '137565283895',
    projectId: 'asianlink-b0111',
    authDomain: 'asianlink-b0111.firebaseapp.com',
    storageBucket: 'asianlink-b0111.firebasestorage.app',
    measurementId: 'G-NKKX3K05DB',
  );
}
